name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    environment: ENV_FILE_TEST

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Setup env test file
      run: |
        cat <<EOF > .env.test
        DATABASE_URL="${{ secrets.DATABASE_URL }}"
        ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}"
        JWT_PRIVATE_KEY="${{ secrets.JWT_PRIVATE_KEY }}"
        JWT_PUBLIC_KEY="${{ secrets.JWT_PUBLIC_KEY }}"
        NODE_ENV="${{ secrets.NODE_ENV }}"
        PORT="${{ secrets.PORT }}"
        TWOFA_APP_NAME="${{ secrets.TWOFA_APP_NAME }}"
        EOF

    - name: Start database
      run: docker compose -f docker-compose.test.yml --env-file ./.env.test up -d

    - name: Wait for Postgres
      run: |
        echo "⏳ Esperando o Postgres ficar pronto..."
        for i in {1..15}; do
          if docker exec $(docker ps -qf "name=pgsql") pg_isready -U docker; then
            echo "✅ Postgres está pronto!"
            exit 0
          fi
          echo "Ainda não pronto, tentando novamente..."
          sleep 5
        done
        echo "❌ Postgres não subiu a tempo."
        exit 1

    - name: Run e2e tests
      run: pnpm test:e2e

    - name: Generate Tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: marquescript/twoFa-api:${{ steps.generate_tag.outputs.sha }},marquescript/twoFa-api:latest